db_uri: mongodb://10.10.0.2/open5gs
logger:
  file:
    path: /open5gs/install/var/log/open5gs/pcf.log

global:
  max:
    ue: 1024

pcf:
  sbi:
    server:
      - address: 10.10.0.13
        port: 7777
    client:
      scp:
        - uri: http://10.10.0.200:7777
